### ISSUE TITLE
issue fittizio

### ISSUE THREAD

**Issue by marte-git** [mattia-gh/primo-compito#1]
uhm ... forse dovevo specificare meglio le istruzioni

ad esempio 
- mettere i file cgi in una directory "cgiFile-COGNOME-NOME" da inserire nel cgi-bin del server usato per la correzione ...
- nella action della form indicare l'indirizzo del file eseguibile secondo la specifica sopra

su classroom va bene cosi'

Qui magari modifichi il codice del file html
1) rendendolo un po' piu' ordinato e leggibile (ad esempio per trovare la form a vista ce ne vuole ...)
2) scrivendo la chiamata come nelle istruzioni sopra.

Poi l;issue si potra' considerare risolto e lo chiuderemo

**Comment by mattia-gh** [comment]
fatto prof
